06.08.2016 10:17:08 recv 1fd1416 error WSAECONNRESET
06.08.2016 10:50:07 poll bell <WinBell 45d2f10 r=748 w=756>
06.08.2016 10:50:07 connect 1fd800 ('127.0.0.1', 4001)
06.08.2016 10:50:07 conn=1fd800 sending protocol version
06.08.2016 10:50:07 conn=1fd800 sending identification
06.08.2016 10:50:07 recv 1fd800 len=24
06.08.2016 10:50:07 recv packet 1fd800 len=5
06.08.2016 10:50:07 conn=1fd800 remote version 1
06.08.2016 10:50:07 recv packet 1fd800 len=11
06.08.2016 10:50:07 conn=1fd800 remote ident 'Controller'
06.08.2016 10:50:07 ready to send 1fd800 (last send len=9)
06.08.2016 10:50:07 ready to send 1fd800 (last send len=12)
06.08.2016 10:50:08 ready to send 1fd800 (last send len=56)
06.08.2016 10:50:08 recv 1fd800 len=23360
06.08.2016 10:50:08 recv 1fd800 len=24820
06.08.2016 10:50:08 recv 1fd800 len=22930
06.08.2016 10:50:08 recv packet 1fd800 len=71106
06.08.2016 11:01:49 ready to send 1fd800 (last send len=222)
06.08.2016 11:01:49 recv 1fd800 len=53
06.08.2016 11:01:49 recv packet 1fd800 len=49
06.08.2016 11:01:49 disconnect 1fd800 
06.08.2016 11:01:49 unrecognized token: "["
Traceback (most recent call last):
  File "C:\TMV3\Lib\DB_Handler_TPL3.py", line 541, in read
    "WHERE [Lines].[LineID] = " + str(self.line_id))
sqlite3.OperationalError: unrecognized token: "["
06.08.2016 11:26:52 poll bell <WinBell 45f0f50 r=748 w=756>
06.08.2016 11:26:52 connect 1fd800 ('127.0.0.1', 4001)
06.08.2016 11:26:52 conn=1fd800 sending protocol version
06.08.2016 11:26:52 conn=1fd800 sending identification
06.08.2016 11:26:52 recv 1fd800 len=24
06.08.2016 11:26:52 recv packet 1fd800 len=5
06.08.2016 11:26:52 conn=1fd800 remote version 1
06.08.2016 11:26:52 recv packet 1fd800 len=11
06.08.2016 11:26:52 conn=1fd800 remote ident 'Controller'
06.08.2016 11:26:52 ready to send 1fd800 (last send len=9)
06.08.2016 11:26:52 ready to send 1fd800 (last send len=12)
06.08.2016 11:26:52 ready to send 1fd800 (last send len=56)
06.08.2016 11:26:52 recv 1fd800 len=24820
06.08.2016 11:26:52 recv 1fd800 len=33580
06.08.2016 11:26:52 recv 1fd800 len=12710
06.08.2016 11:26:52 recv packet 1fd800 len=71106
06.08.2016 11:54:25 poll bell <WinBell 45e0bf0 r=852 w=796>
06.08.2016 11:54:25 connect 1fd960 ('127.0.0.1', 4001)
06.08.2016 11:54:25 conn=1fd960 sending protocol version
06.08.2016 11:54:25 conn=1fd960 sending identification
06.08.2016 11:54:25 recv 1fd960 len=24
06.08.2016 11:54:25 recv packet 1fd960 len=5
06.08.2016 11:54:25 conn=1fd960 remote version 1
06.08.2016 11:54:25 recv packet 1fd960 len=11
06.08.2016 11:54:25 conn=1fd960 remote ident 'Controller'
06.08.2016 11:54:25 ready to send 1fd960 (last send len=9)
06.08.2016 11:54:25 ready to send 1fd960 (last send len=12)
06.08.2016 11:54:26 ready to send 1fd960 (last send len=56)
06.08.2016 11:54:26 recv 1fd960 len=24820
06.08.2016 11:54:26 recv 1fd960 len=23360
06.08.2016 11:54:26 recv 1fd960 len=22930
06.08.2016 11:54:26 recv packet 1fd960 len=71106
06.08.2016 11:58:15 poll bell <WinBell 45e2c70 r=868 w=820>
06.08.2016 11:58:15 connect 1fd956 ('127.0.0.1', 4001)
06.08.2016 11:58:15 conn=1fd956 sending protocol version
06.08.2016 11:58:15 conn=1fd956 sending identification
06.08.2016 11:58:15 recv 1fd956 len=24
06.08.2016 11:58:15 recv packet 1fd956 len=5
06.08.2016 11:58:15 conn=1fd956 remote version 1
06.08.2016 11:58:16 recv packet 1fd956 len=11
06.08.2016 11:58:16 conn=1fd956 remote ident 'Controller'
06.08.2016 11:58:16 ready to send 1fd956 (last send len=9)
06.08.2016 11:58:16 ready to send 1fd956 (last send len=12)
06.08.2016 11:58:16 ready to send 1fd956 (last send len=56)
06.08.2016 11:58:16 recv 1fd956 len=27740
06.08.2016 11:58:16 recv 1fd956 len=24820
06.08.2016 11:58:16 recv 1fd956 len=18550
06.08.2016 11:58:16 recv packet 1fd956 len=71106
06.08.2016 01:38:54 poll bell <WinBell 4601f90 r=760 w=752>
06.08.2016 01:38:54 connect 1fd804 ('127.0.0.1', 4001)
06.08.2016 01:38:54 conn=1fd804 sending protocol version
06.08.2016 01:38:54 conn=1fd804 sending identification
06.08.2016 01:38:54 recv 1fd804 len=24
06.08.2016 01:38:54 recv packet 1fd804 len=5
06.08.2016 01:38:54 conn=1fd804 remote version 1
06.08.2016 01:38:54 recv packet 1fd804 len=11
06.08.2016 01:38:54 conn=1fd804 remote ident 'Controller'
06.08.2016 01:38:54 ready to send 1fd804 (last send len=9)
06.08.2016 01:38:54 ready to send 1fd804 (last send len=12)
06.08.2016 01:38:54 ready to send 1fd804 (last send len=56)
06.08.2016 01:38:54 recv 1fd804 len=23360
06.08.2016 01:38:54 recv 1fd804 len=27740
06.08.2016 01:38:54 recv 1fd804 len=20010
06.08.2016 01:38:54 recv packet 1fd804 len=71106
06.08.2016 04:24:34 poll bell <WinBell 4651fb0 r=760 w=752>
06.08.2016 04:24:34 connect 1fd804 ('127.0.0.1', 4001)
06.08.2016 04:24:34 conn=1fd804 sending protocol version
06.08.2016 04:24:34 conn=1fd804 sending identification
06.08.2016 04:24:34 recv 1fd804 len=24
06.08.2016 04:24:34 recv packet 1fd804 len=5
06.08.2016 04:24:34 conn=1fd804 remote version 1
06.08.2016 04:24:34 recv packet 1fd804 len=11
06.08.2016 04:24:34 conn=1fd804 remote ident 'Controller'
06.08.2016 04:24:34 ready to send 1fd804 (last send len=9)
06.08.2016 04:24:34 ready to send 1fd804 (last send len=12)
06.08.2016 04:24:35 ready to send 1fd804 (last send len=56)
06.08.2016 04:24:35 recv 1fd804 len=32120
06.08.2016 04:24:35 recv 1fd804 len=32120
06.08.2016 04:24:35 recv 1fd804 len=6870
06.08.2016 04:24:35 recv packet 1fd804 len=71106
06.08.2016 04:43:03 poll bell <WinBell 462ff90 r=760 w=752>
06.08.2016 04:43:03 connect 1fd804 ('127.0.0.1', 4001)
06.08.2016 04:43:03 conn=1fd804 sending protocol version
06.08.2016 04:43:03 conn=1fd804 sending identification
06.08.2016 04:43:03 recv 1fd804 len=24
06.08.2016 04:43:03 recv packet 1fd804 len=5
06.08.2016 04:43:03 conn=1fd804 remote version 1
06.08.2016 04:43:03 recv packet 1fd804 len=11
06.08.2016 04:43:03 conn=1fd804 remote ident 'Controller'
06.08.2016 04:43:03 ready to send 1fd804 (last send len=9)
06.08.2016 04:43:03 ready to send 1fd804 (last send len=12)
06.08.2016 04:43:03 ready to send 1fd804 (last send len=56)
06.08.2016 04:43:03 recv 1fd804 len=23360
06.08.2016 04:43:03 recv 1fd804 len=23360
06.08.2016 04:43:03 recv 1fd804 len=23360
06.08.2016 04:43:03 recv 1fd804 len=1030
06.08.2016 04:43:03 recv packet 1fd804 len=71106
06.08.2016 04:43:10 recv 1fd1432 error WSAECONNRESET
06.13.2016 07:11:14 poll bell <WinBell 4625f70 r=752 w=760>
06.13.2016 07:11:14 connect 1fd804 ('127.0.0.1', 4001)
06.13.2016 07:11:14 conn=1fd804 sending protocol version
06.13.2016 07:11:14 conn=1fd804 sending identification
06.13.2016 07:11:14 recv 1fd804 len=24
06.13.2016 07:11:14 recv packet 1fd804 len=5
06.13.2016 07:11:14 conn=1fd804 remote version 1
06.13.2016 07:11:14 recv packet 1fd804 len=11
06.13.2016 07:11:14 conn=1fd804 remote ident 'Controller'
06.13.2016 07:11:14 ready to send 1fd804 (last send len=9)
06.13.2016 07:11:14 ready to send 1fd804 (last send len=12)
06.13.2016 07:11:14 ready to send 1fd804 (last send len=56)
06.13.2016 07:11:14 near "<": syntax error
Traceback (most recent call last):
  File "C:\TMV3\Lib\DB_Handler_TPL3.py", line 781, in readCorrIDs
    "WHERE [Plot].[PlotID] = {0}".format(str(plotID)))
sqlite3.OperationalError: near "<": syntax error
06.13.2016 07:12:25 poll bell <WinBell 46a2f70 r=752 w=760>
06.13.2016 07:12:25 connect 1fd804 ('127.0.0.1', 4001)
06.13.2016 07:12:25 conn=1fd804 sending protocol version
06.13.2016 07:12:25 conn=1fd804 sending identification
06.13.2016 07:12:25 recv 1fd804 len=24
06.13.2016 07:12:25 recv packet 1fd804 len=5
06.13.2016 07:12:25 conn=1fd804 remote version 1
06.13.2016 07:12:25 recv packet 1fd804 len=11
06.13.2016 07:12:25 conn=1fd804 remote ident 'Controller'
06.13.2016 07:12:25 ready to send 1fd804 (last send len=9)
06.13.2016 07:12:25 ready to send 1fd804 (last send len=12)
06.13.2016 07:12:25 ready to send 1fd804 (last send len=56)
06.13.2016 07:12:25 near "<": syntax error
Traceback (most recent call last):
  File "C:\TMV3\Lib\DB_Handler_TPL3.py", line 781, in readCorrIDs
    "WHERE [Plot].[PlotID] = {0}".format(str(plotID)))
sqlite3.OperationalError: near "<": syntax error
06.13.2016 07:12:25 recv 1fd804 len=23360
06.13.2016 07:12:25 recv 1fd804 len=23360
06.13.2016 07:12:26 recv 1fd804 len=23360
06.13.2016 07:12:26 recv 1fd804 len=1030
06.13.2016 07:12:26 recv packet 1fd804 len=71106
06.13.2016 07:14:01 poll bell <WinBell 5163310 r=864 w=860>
06.13.2016 07:14:01 connect 1fd908 ('127.0.0.1', 4001)
06.13.2016 07:14:01 conn=1fd908 sending protocol version
06.13.2016 07:14:01 conn=1fd908 sending identification
06.13.2016 07:14:01 recv 1fd908 len=24
06.13.2016 07:14:01 recv packet 1fd908 len=5
06.13.2016 07:14:01 conn=1fd908 remote version 1
06.13.2016 07:14:01 recv packet 1fd908 len=11
06.13.2016 07:14:01 conn=1fd908 remote ident 'Controller'
06.13.2016 07:14:01 ready to send 1fd908 (last send len=9)
06.13.2016 07:14:01 ready to send 1fd908 (last send len=12)
06.13.2016 07:14:02 ready to send 1fd908 (last send len=56)
06.13.2016 07:15:25 poll bell <WinBell 5103310 r=864 w=860>
06.13.2016 07:15:25 connect 1fd908 ('127.0.0.1', 4001)
06.13.2016 07:15:25 conn=1fd908 sending protocol version
06.13.2016 07:15:25 conn=1fd908 sending identification
06.13.2016 07:15:25 ready to send 1fd908 (last send len=9)
06.13.2016 07:15:25 recv 1fd908 len=24
06.13.2016 07:15:25 recv packet 1fd908 len=5
06.13.2016 07:15:25 conn=1fd908 remote version 1
06.13.2016 07:15:25 recv packet 1fd908 len=11
06.13.2016 07:15:25 conn=1fd908 remote ident 'Controller'
06.13.2016 07:15:25 ready to send 1fd908 (last send len=12)
06.13.2016 07:15:26 ready to send 1fd908 (last send len=56)
06.13.2016 07:16:37 poll bell <WinBell 5134310 r=864 w=860>
06.13.2016 07:16:37 connect 1fd908 ('127.0.0.1', 4001)
06.13.2016 07:16:37 conn=1fd908 sending protocol version
06.13.2016 07:16:37 conn=1fd908 sending identification
06.13.2016 07:16:37 recv 1fd908 len=24
06.13.2016 07:16:37 recv packet 1fd908 len=5
06.13.2016 07:16:37 conn=1fd908 remote version 1
06.13.2016 07:16:37 recv packet 1fd908 len=11
06.13.2016 07:16:37 conn=1fd908 remote ident 'Controller'
06.13.2016 07:16:37 ready to send 1fd908 (last send len=9)
06.13.2016 07:16:37 ready to send 1fd908 (last send len=12)
06.13.2016 07:16:38 ready to send 1fd908 (last send len=56)
06.13.2016 07:18:07 poll bell <WinBell 5102350 r=868 w=864>
06.13.2016 07:18:07 connect 1fd912 ('127.0.0.1', 4001)
06.13.2016 07:18:07 conn=1fd912 sending protocol version
06.13.2016 07:18:07 conn=1fd912 sending identification
06.13.2016 07:18:07 recv 1fd912 len=24
06.13.2016 07:18:07 recv packet 1fd912 len=5
06.13.2016 07:18:07 conn=1fd912 remote version 1
06.13.2016 07:18:07 recv packet 1fd912 len=11
06.13.2016 07:18:07 conn=1fd912 remote ident 'Controller'
06.13.2016 07:18:07 ready to send 1fd912 (last send len=9)
06.13.2016 07:18:07 ready to send 1fd912 (last send len=12)
06.13.2016 07:18:07 ready to send 1fd912 (last send len=56)
06.13.2016 07:20:03 poll bell <WinBell 5132350 r=864 w=860>
06.13.2016 07:20:03 connect 1fd908 ('127.0.0.1', 4001)
06.13.2016 07:20:03 conn=1fd908 sending protocol version
06.13.2016 07:20:03 conn=1fd908 sending identification
06.13.2016 07:20:03 recv 1fd908 len=24
06.13.2016 07:20:03 recv packet 1fd908 len=5
06.13.2016 07:20:03 conn=1fd908 remote version 1
06.13.2016 07:20:03 recv packet 1fd908 len=11
06.13.2016 07:20:03 conn=1fd908 remote ident 'Controller'
06.13.2016 07:20:03 ready to send 1fd908 (last send len=9)
06.13.2016 07:20:03 ready to send 1fd908 (last send len=12)
06.13.2016 07:20:04 ready to send 1fd908 (last send len=56)
06.13.2016 07:20:41 poll bell <WinBell 51c1350 r=864 w=860>
06.13.2016 07:20:41 connect 1fd908 ('127.0.0.1', 4001)
06.13.2016 07:20:41 conn=1fd908 sending protocol version
06.13.2016 07:20:41 conn=1fd908 sending identification
06.13.2016 07:20:41 recv 1fd908 len=24
06.13.2016 07:20:41 recv packet 1fd908 len=5
06.13.2016 07:20:41 conn=1fd908 remote version 1
06.13.2016 07:20:41 recv packet 1fd908 len=11
06.13.2016 07:20:41 conn=1fd908 remote ident 'Controller'
06.13.2016 07:20:41 ready to send 1fd908 (last send len=9)
06.13.2016 07:20:41 ready to send 1fd908 (last send len=12)
06.13.2016 07:20:42 ready to send 1fd908 (last send len=56)
06.13.2016 07:21:34 recv 1fd908 len=23360
06.13.2016 07:21:34 recv 1fd908 len=23360
06.13.2016 07:21:34 recv 1fd908 len=23360
06.13.2016 07:21:34 recv 1fd908 len=1030
06.13.2016 07:21:34 recv packet 1fd908 len=71106
06.13.2016 07:22:07 poll bell <WinBell 50f2330 r=864 w=860>
06.13.2016 07:22:07 connect 1fd908 ('127.0.0.1', 4001)
06.13.2016 07:22:07 conn=1fd908 sending protocol version
06.13.2016 07:22:07 conn=1fd908 sending identification
06.13.2016 07:22:07 ready to send 1fd908 (last send len=9)
06.13.2016 07:22:07 recv 1fd908 len=24
06.13.2016 07:22:07 recv packet 1fd908 len=5
06.13.2016 07:22:07 conn=1fd908 remote version 1
06.13.2016 07:22:07 recv packet 1fd908 len=11
06.13.2016 07:22:07 conn=1fd908 remote ident 'Controller'
06.13.2016 07:22:07 ready to send 1fd908 (last send len=13)
06.13.2016 07:22:07 ready to send 1fd908 (last send len=56)
06.13.2016 07:34:15 poll bell <WinBell 4691f70 r=752 w=760>
06.13.2016 07:34:15 connect 1fd804 ('127.0.0.1', 4001)
06.13.2016 07:34:15 conn=1fd804 sending protocol version
06.13.2016 07:34:15 conn=1fd804 sending identification
06.13.2016 07:34:15 recv 1fd804 len=24
06.13.2016 07:34:15 recv packet 1fd804 len=5
06.13.2016 07:34:15 conn=1fd804 remote version 1
06.13.2016 07:34:15 recv packet 1fd804 len=11
06.13.2016 07:34:15 conn=1fd804 remote ident 'Controller'
06.13.2016 07:34:15 ready to send 1fd804 (last send len=9)
06.13.2016 07:34:15 ready to send 1fd804 (last send len=12)
06.13.2016 07:34:15 ready to send 1fd804 (last send len=56)
06.13.2016 07:34:15 recv 1fd804 len=23360
06.13.2016 07:34:15 recv 1fd804 len=23360
06.13.2016 07:34:15 recv 1fd804 len=23360
06.13.2016 07:34:15 recv 1fd804 len=1033
06.13.2016 07:34:15 recv packet 1fd804 len=71109
06.13.2016 07:34:16 recv 1fd804 len=53
06.13.2016 07:34:16 recv packet 1fd804 len=49
06.13.2016 07:34:16 disconnect 1fd804 
06.13.2016 07:36:11 poll bell <WinBell 4634f70 r=760 w=752>
06.13.2016 07:36:11 connect 1fd804 ('127.0.0.1', 4001)
06.13.2016 07:36:11 conn=1fd804 sending protocol version
06.13.2016 07:36:11 conn=1fd804 sending identification
06.13.2016 07:36:11 recv 1fd804 len=24
06.13.2016 07:36:11 recv packet 1fd804 len=5
06.13.2016 07:36:11 conn=1fd804 remote version 1
06.13.2016 07:36:11 recv packet 1fd804 len=11
06.13.2016 07:36:11 conn=1fd804 remote ident 'Controller'
06.13.2016 07:36:11 ready to send 1fd804 (last send len=9)
06.13.2016 07:36:11 ready to send 1fd804 (last send len=12)
06.13.2016 07:36:11 ready to send 1fd804 (last send len=56)
06.13.2016 07:36:11 recv 1fd804 len=23360
06.13.2016 07:36:11 recv 1fd804 len=23360
06.13.2016 07:36:11 recv 1fd804 len=23360
06.13.2016 07:36:11 recv 1fd804 len=1033
06.13.2016 07:36:11 recv packet 1fd804 len=71109
06.13.2016 10:06:40 'MainForm' object has no attribute 'cutFreqX1'
Traceback (most recent call last):
  File "Graph.py", line 871, in cutRange
    if (x[0] >= self.cutFreqX1) and (x[0] <= self.cutFreqX2):
AttributeError: 'MainForm' object has no attribute 'cutFreqX1'
06.13.2016 10:12:49 unorderable types: str() >= float()
Traceback (most recent call last):
  File "Graph.py", line 871, in cutRange
    if (x[0] >= cutFreqA) and (x[0] <= cutFreqB):
TypeError: unorderable types: str() >= float()
06.13.2016 10:12:49 eval() arg 1 must be a string, bytes or code object
Traceback (most recent call last):
  File "Graph.py", line 656, in onNewLine
    _xyf = eval(data.data_xy)
TypeError: eval() arg 1 must be a string, bytes or code object
06.13.2016 10:15:10 unorderable types: str() >= float()
Traceback (most recent call last):
  File "Graph.py", line 871, in cutRange
    if (x[0] >= cutFreqA) and (x[0] <= cutFreqB):
TypeError: unorderable types: str() >= float()
06.13.2016 10:15:10 eval() arg 1 must be a string, bytes or code object
Traceback (most recent call last):
  File "Graph.py", line 656, in onNewLine
    _xyf = eval(data.data_xy)
TypeError: eval() arg 1 must be a string, bytes or code object
06.13.2016 10:19:07 eval() arg 1 must be a string, bytes or code object
Traceback (most recent call last):
  File "Graph.py", line 656, in onNewLine
    _xyf = eval(data.data_xy)
TypeError: eval() arg 1 must be a string, bytes or code object
06.13.2016 11:16:04 malformed node or string: [(1000000000.0, 23.7), (1500000000.0, 25.1), (2000000000.0, 27.5)]
Traceback (most recent call last):
  File "Graph.py", line 571, in onShowPlot
    dxy = self.cutRange(line.data_xy,_t.x1,_t.x2)
  File "Graph.py", line 816, in cutRange
    _data = ast.literal_eval(data)
  File "C:\Python34\lib\ast.py", line 84, in literal_eval
    return _convert(node_or_string)
  File "C:\Python34\lib\ast.py", line 83, in _convert
    raise ValueError('malformed node or string: ' + repr(node))
ValueError: malformed node or string: [(1000000000.0, 23.7), (1500000000.0, 25.1), (2000000000.0, 27.5)]
06.13.2016 11:18:19 malformed node or string: [(1000000000.0, 23.7), (1500000000.0, 25.1), (2000000000.0, 27.5)]
Traceback (most recent call last):
  File "Graph.py", line 571, in onShowPlot
    dxy = self.cutRange(line.data_xy,_t.x1,_t.x2)
  File "Graph.py", line 816, in cutRange
    _data = ast.literal_eval(data)
  File "C:\Python34\lib\ast.py", line 84, in literal_eval
    return _convert(node_or_string)
  File "C:\Python34\lib\ast.py", line 83, in _convert
    raise ValueError('malformed node or string: ' + repr(node))
ValueError: malformed node or string: [(1000000000.0, 23.7), (1500000000.0, 25.1), (2000000000.0, 27.5)]
06.13.2016 11:23:59 need more than 1 value to unpack
Traceback (most recent call last):
  File "Graph.py", line 667, in onNewLine
    _x, _y = zip(*_xys)
ValueError: need more than 1 value to unpack
06.13.2016 11:23:59 need more than 1 value to unpack
Traceback (most recent call last):
  File "Graph.py", line 667, in onNewLine
    _x, _y = zip(*_xys)
ValueError: need more than 1 value to unpack
06.13.2016 11:23:59 need more than 1 value to unpack
Traceback (most recent call last):
  File "Graph.py", line 667, in onNewLine
    _x, _y = zip(*_xys)
ValueError: need more than 1 value to unpack
06.13.2016 11:23:59 need more than 1 value to unpack
Traceback (most recent call last):
  File "Graph.py", line 667, in onNewLine
    _x, _y = zip(*_xys)
ValueError: need more than 1 value to unpack
06.13.2016 11:23:59 need more than 1 value to unpack
Traceback (most recent call last):
  File "Graph.py", line 667, in onNewLine
    _x, _y = zip(*_xys)
ValueError: need more than 1 value to unpack
06.13.2016 11:23:59 need more than 1 value to unpack
Traceback (most recent call last):
  File "Graph.py", line 667, in onNewLine
    _x, _y = zip(*_xys)
ValueError: need more than 1 value to unpack
06.13.2016 11:23:59 need more than 1 value to unpack
Traceback (most recent call last):
  File "Graph.py", line 667, in onNewLine
    _x, _y = zip(*_xys)
ValueError: need more than 1 value to unpack
06.13.2016 11:23:59 need more than 1 value to unpack
Traceback (most recent call last):
  File "Graph.py", line 667, in onNewLine
    _x, _y = zip(*_xys)
ValueError: need more than 1 value to unpack
06.13.2016 11:23:59 need more than 1 value to unpack
Traceback (most recent call last):
  File "Graph.py", line 667, in onNewLine
    _x, _y = zip(*_xys)
ValueError: need more than 1 value to unpack
06.13.2016 11:23:59 need more than 1 value to unpack
Traceback (most recent call last):
  File "Graph.py", line 667, in onNewLine
    _x, _y = zip(*_xys)
ValueError: need more than 1 value to unpack
06.13.2016 11:23:59 'Tpl3Lines' object has no attribute 'Type'
Traceback (most recent call last):
  File "Graph.py", line 578, in onShowPlot
    if _line.Type == 'Antenna': pass
AttributeError: 'Tpl3Lines' object has no attribute 'Type'
06.13.2016 11:27:53 malformed node or string: [(1000000000.0, 23.7), (1500000000.0, 25.1), (2000000000.0, 27.5)]
Traceback (most recent call last):
  File "Graph.py", line 572, in onShowPlot
    dxy = self.cutRange(line.data_xy,_t.x1,_t.x2)
  File "Graph.py", line 817, in cutRange
    _data = ast.literal_eval(data)
  File "C:\Python34\lib\ast.py", line 84, in literal_eval
    return _convert(node_or_string)
  File "C:\Python34\lib\ast.py", line 83, in _convert
    raise ValueError('malformed node or string: ' + repr(node))
ValueError: malformed node or string: [(1000000000.0, 23.7), (1500000000.0, 25.1), (2000000000.0, 27.5)]
06.13.2016 11:28:40 'Tpl3Lines' object has no attribute 'copy'
Traceback (most recent call last):
  File "Graph.py", line 573, in onShowPlot
    dline = line.copy()
AttributeError: 'Tpl3Lines' object has no attribute 'copy'
06.13.2016 11:30:53 'module' object is not callable
Traceback (most recent call last):
  File "Graph.py", line 574, in onShowPlot
    dline = copy(line)
TypeError: 'module' object is not callable
06.13.2016 11:31:31 'Tpl3Lines' object has no attribute 'Type'
Traceback (most recent call last):
  File "Graph.py", line 579, in onShowPlot
    if _line.Type == 'Antenna': pass
AttributeError: 'Tpl3Lines' object has no attribute 'Type'
06.13.2016 02:14:33 'Tpl3Lines' object has no attribute 'Type'
Traceback (most recent call last):
  File "Graph.py", line 579, in onShowPlot
    if _line.Type == 'Antenna': pass
AttributeError: 'Tpl3Lines' object has no attribute 'Type'
06.13.2016 02:21:07 'Tpl3Lines' object has no attribute 'Type'
Traceback (most recent call last):
  File "Graph.py", line 579, in onShowPlot
    if _line.Type == 'Antenna': pass
AttributeError: 'Tpl3Lines' object has no attribute 'Type'
06.13.2016 02:24:05 'Tpl3Lines' object has no attribute 'Type'
Traceback (most recent call last):
  File "Graph.py", line 579, in onShowPlot
    if _line.Type == 'Antenna': pass
AttributeError: 'Tpl3Lines' object has no attribute 'Type'
06.13.2016 03:38:19 'Tpl3Lines' object has no attribute 'Type'
Traceback (most recent call last):
  File "Graph.py", line 579, in onShowPlot
    if _line.Type == 'Antenna': pass
AttributeError: 'Tpl3Lines' object has no attribute 'Type'
06.13.2016 03:41:02 'Tpl3Lines' object has no attribute 'Type'
Traceback (most recent call last):
  File "Graph.py", line 579, in onShowPlot
    if _line.Type == 'Antenna': pass
AttributeError: 'Tpl3Lines' object has no attribute 'Type'
06.13.2016 03:48:10 need more than 1 value to unpack
Traceback (most recent call last):
  File "Graph.py", line 668, in onNewLine
    _x, _y = zip(*_xys)
ValueError: need more than 1 value to unpack
06.13.2016 03:48:10 need more than 1 value to unpack
Traceback (most recent call last):
  File "Graph.py", line 668, in onNewLine
    _x, _y = zip(*_xys)
ValueError: need more than 1 value to unpack
06.13.2016 03:48:10 need more than 1 value to unpack
Traceback (most recent call last):
  File "Graph.py", line 668, in onNewLine
    _x, _y = zip(*_xys)
ValueError: need more than 1 value to unpack
06.13.2016 04:30:08 'MainForm' object has no attribute 'corrProbeYEndPos'
Traceback (most recent call last):
  File "Graph.py", line 596, in onShowPlot
    if self.corrProbeYEndPos > 0:
AttributeError: 'MainForm' object has no attribute 'corrProbeYEndPos'
06.13.2016 05:27:17 recv 1fd1444 error WSAECONNRESET
06.13.2016 05:29:07 'MainForm' object has no attribute 'corrProbeYEndPos'
Traceback (most recent call last):
  File "Graph.py", line 596, in onShowPlot
    if self.corrProbeYEndPos > 0:
AttributeError: 'MainForm' object has no attribute 'corrProbeYEndPos'
06.13.2016 05:30:01 recv 1fd1420 error WSAECONNRESET
06.14.2016 07:52:15 'MainForm' object has no attribute 'corrProbeYEndPos'
Traceback (most recent call last):
  File "Graph.py", line 599, in onShowPlot
    if self.corrProbeYEndPos > 0:
AttributeError: 'MainForm' object has no attribute 'corrProbeYEndPos'
06.14.2016 07:56:40 'MainForm' object has no attribute 'corrProbeYEndPos'
Traceback (most recent call last):
  File "Graph.py", line 599, in onShowPlot
    if self.corrProbeYEndPos > 0:
AttributeError: 'MainForm' object has no attribute 'corrProbeYEndPos'
06.14.2016 07:56:55 recv 1fd1456 error WSAECONNRESET
06.14.2016 07:57:08 'MainForm' object has no attribute 'corrProbeYEndPos'
Traceback (most recent call last):
  File "Graph.py", line 599, in onShowPlot
    if self.corrProbeYEndPos > 0:
AttributeError: 'MainForm' object has no attribute 'corrProbeYEndPos'
06.14.2016 10:07:09 'MainForm' object has no attribute 'corrProbeYEndPos'
Traceback (most recent call last):
  File "Graph.py", line 599, in onShowPlot
    if self.corrProbeYEndPos > 0:
AttributeError: 'MainForm' object has no attribute 'corrProbeYEndPos'
06.14.2016 10:07:40 recv 1fd1424 error WSAECONNRESET
06.14.2016 10:09:03 'MainForm' object has no attribute 'corrProbeYEndPos'
Traceback (most recent call last):
  File "Graph.py", line 600, in onShowPlot
    if self.corrProbeYEndPos > 0:
AttributeError: 'MainForm' object has no attribute 'corrProbeYEndPos'
06.14.2016 10:11:51 'MainForm' object has no attribute 'corrProbeYEndPos'
Traceback (most recent call last):
  File "Graph.py", line 600, in onShowPlot
    if self.corrProbeYEndPos > 0:
AttributeError: 'MainForm' object has no attribute 'corrProbeYEndPos'
06.14.2016 10:12:29 'MainForm' object has no attribute 'corrProbeYEndPos'
Traceback (most recent call last):
  File "Graph.py", line 600, in onShowPlot
    if self.corrProbeYEndPos > 0:
AttributeError: 'MainForm' object has no attribute 'corrProbeYEndPos'
06.14.2016 10:13:27 recv 1fd1440 error WSAECONNRESET
06.14.2016 10:14:57 'MainForm' object has no attribute 'corrProbeYEndPos'
Traceback (most recent call last):
  File "Graph.py", line 600, in onShowPlot
    if self.corrProbeYEndPos > 0:
AttributeError: 'MainForm' object has no attribute 'corrProbeYEndPos'
06.14.2016 11:39:39 'MainForm' object has no attribute 'corrProbeYEndPos'
Traceback (most recent call last):
  File "Graph.py", line 605, in onShowPlot
    if self.corrProbeYEndPos > 0:
AttributeError: 'MainForm' object has no attribute 'corrProbeYEndPos'
06.14.2016 11:42:10 recv 1fd1416 error WSAECONNRESET
06.14.2016 02:19:35 'MainForm' object has no attribute 'corrProbeYEndPos'
Traceback (most recent call last):
  File "Graph.py", line 608, in onShowPlot
    if self.corrProbeYEndPos > 0:
AttributeError: 'MainForm' object has no attribute 'corrProbeYEndPos'
06.14.2016 02:20:23 'MainForm' object has no attribute 'corrProbeYEndPos'
Traceback (most recent call last):
  File "Graph.py", line 608, in onShowPlot
    if self.corrProbeYEndPos > 0:
AttributeError: 'MainForm' object has no attribute 'corrProbeYEndPos'
06.14.2016 02:22:52 'MainForm' object has no attribute 'corrProbeYEndPos'
Traceback (most recent call last):
  File "Graph.py", line 611, in onShowPlot
    if self.corrProbeYEndPos > 0:
AttributeError: 'MainForm' object has no attribute 'corrProbeYEndPos'
06.14.2016 02:45:11 'MainForm' object has no attribute 'corrProbeYEndPos'
Traceback (most recent call last):
  File "Graph.py", line 626, in onShowPlot
    if self.corrProbeYEndPos > 0:
AttributeError: 'MainForm' object has no attribute 'corrProbeYEndPos'
06.14.2016 02:51:27 'MainForm' object has no attribute 'corrProbeYEndPos'
Traceback (most recent call last):
  File "Graph.py", line 625, in onShowPlot
    if self.corrProbeYEndPos > 0:
AttributeError: 'MainForm' object has no attribute 'corrProbeYEndPos'
06.14.2016 03:04:43 'Line2D' object does not support indexing
Traceback (most recent call last):
  File "Graph.py", line 736, in onNewLine
    line[0].set_picker(True)
TypeError: 'Line2D' object does not support indexing
06.14.2016 03:04:43 'Line2D' object does not support indexing
Traceback (most recent call last):
  File "Graph.py", line 736, in onNewLine
    line[0].set_picker(True)
TypeError: 'Line2D' object does not support indexing
06.14.2016 03:04:43 'Line2D' object does not support indexing
Traceback (most recent call last):
  File "Graph.py", line 736, in onNewLine
    line[0].set_picker(True)
TypeError: 'Line2D' object does not support indexing
06.14.2016 03:04:43 'Line2D' object does not support indexing
Traceback (most recent call last):
  File "Graph.py", line 736, in onNewLine
    line[0].set_picker(True)
TypeError: 'Line2D' object does not support indexing
06.14.2016 03:04:43 'Line2D' object does not support indexing
Traceback (most recent call last):
  File "Graph.py", line 736, in onNewLine
    line[0].set_picker(True)
TypeError: 'Line2D' object does not support indexing
06.14.2016 03:04:43 'Line2D' object does not support indexing
Traceback (most recent call last):
  File "Graph.py", line 736, in onNewLine
    line[0].set_picker(True)
TypeError: 'Line2D' object does not support indexing
06.14.2016 03:04:43 'Line2D' object does not support indexing
Traceback (most recent call last):
  File "Graph.py", line 736, in onNewLine
    line[0].set_picker(True)
TypeError: 'Line2D' object does not support indexing
06.14.2016 03:04:43 'Line2D' object does not support indexing
Traceback (most recent call last):
  File "Graph.py", line 736, in onNewLine
    line[0].set_picker(True)
TypeError: 'Line2D' object does not support indexing
06.14.2016 03:04:43 'Line2D' object does not support indexing
Traceback (most recent call last):
  File "Graph.py", line 736, in onNewLine
    line[0].set_picker(True)
TypeError: 'Line2D' object does not support indexing
06.14.2016 03:04:43 'Line2D' object does not support indexing
Traceback (most recent call last):
  File "Graph.py", line 736, in onNewLine
    line[0].set_picker(True)
TypeError: 'Line2D' object does not support indexing
06.14.2016 03:04:43 'Line2D' object does not support indexing
Traceback (most recent call last):
  File "Graph.py", line 736, in onNewLine
    line[0].set_picker(True)
TypeError: 'Line2D' object does not support indexing
06.14.2016 03:04:43 'Line2D' object does not support indexing
Traceback (most recent call last):
  File "Graph.py", line 736, in onNewLine
    line[0].set_picker(True)
TypeError: 'Line2D' object does not support indexing
06.14.2016 03:04:43 'Line2D' object does not support indexing
Traceback (most recent call last):
  File "Graph.py", line 736, in onNewLine
    line[0].set_picker(True)
TypeError: 'Line2D' object does not support indexing
06.14.2016 03:16:15 recv 1fd1436 error WSAECONNRESET
06.14.2016 03:25:08 recv 1fd1416 error WSAECONNRESET
06.14.2016 03:44:40 recv 1fd1424 error WSAECONNRESET
06.15.2016 03:17:22 recv 1fd1408 error WSAECONNRESET
06.15.2016 07:57:14 recv 1fd1420 error WSAECONNRESET
06.15.2016 10:02:07 TMV3 Measurement started Meas
06.15.2016 10:25:02 recv 1fd956 error WSAECONNRESET
06.15.2016 10:25:22 TMV3 Measurement started Meas
06.15.2016 10:39:25 TMV3 Measurement started Meas
06.15.2016 10:47:23 TMV3 Measurement started Meas
06.15.2016 10:47:25 'MainForm' object has no attribute 'corrCableYEndPos'
Traceback (most recent call last):
  File "Graph.py", line 809, in onNewLine
    if self.corrCableYEndPos > 0:
AttributeError: 'MainForm' object has no attribute 'corrCableYEndPos'
06.15.2016 10:47:25 'MainForm' object has no attribute 'corrCableYEndPos'
Traceback (most recent call last):
  File "Graph.py", line 809, in onNewLine
    if self.corrCableYEndPos > 0:
AttributeError: 'MainForm' object has no attribute 'corrCableYEndPos'
06.15.2016 10:47:25 'MainForm' object has no attribute 'corrCableYEndPos'
Traceback (most recent call last):
  File "Graph.py", line 809, in onNewLine
    if self.corrCableYEndPos > 0:
AttributeError: 'MainForm' object has no attribute 'corrCableYEndPos'
06.15.2016 10:47:25 'MainForm' object has no attribute 'corrCableYEndPos'
Traceback (most recent call last):
  File "Graph.py", line 809, in onNewLine
    if self.corrCableYEndPos > 0:
AttributeError: 'MainForm' object has no attribute 'corrCableYEndPos'
06.15.2016 11:12:12 TMV3 Measurement started Meas
06.15.2016 11:12:14 writeAntLabel() takes 1 positional argument but 2 were given
Traceback (most recent call last):
  File "Graph.py", line 803, in onNewLine
    self.corrLabel.writeAntLabel(self)
TypeError: writeAntLabel() takes 1 positional argument but 2 were given
06.15.2016 11:12:25 recv 2fd1488 error WSAECONNRESET
06.15.2016 11:14:06 TMV3 Measurement started Meas
06.15.2016 11:21:22 TMV3 Measurement started Meas
06.15.2016 11:25:57 recv 2fd1472 error WSAECONNRESET
06.15.2016 11:26:13 TMV3 Measurement started Meas
06.15.2016 11:27:03 recv 2fd1480 error WSAECONNRESET
06.15.2016 11:29:05 TMV3 Measurement started Meas
06.15.2016 11:36:55 TMV3 Measurement started Meas
06.15.2016 11:38:35 recv 2fd1464 error WSAECONNRESET
06.15.2016 11:38:36 recv 1fd944 error WSAECONNRESET
06.15.2016 11:38:36 TMV3 Measurement started Meas
06.15.2016 11:41:41 recv 4fd1768 error WSAECONNRESET
06.15.2016 02:07:24 TMV3 Measurement started Meas
06.15.2016 02:07:26 'NoneType' object has no attribute 'set_axes'
Traceback (most recent call last):
  File "Graph.py", line 805, in onNewLine
    self.corrLabel.writeCabLabel()
  File "Graph.py", line 1054, in writeCabLabel
    self.parent.host.add_artist(self.labelCable)
  File "C:\Python34\lib\site-packages\matplotlib\axes\_base.py", line 1453, in add_artist
    a.set_axes(self)
AttributeError: 'NoneType' object has no attribute 'set_axes'
06.15.2016 02:07:41 'NoneType' object has no attribute 'set_axes'
Traceback (most recent call last):
  File "Graph.py", line 805, in onNewLine
    self.corrLabel.writeCabLabel()
  File "Graph.py", line 1054, in writeCabLabel
    self.parent.host.add_artist(self.labelCable)
  File "C:\Python34\lib\site-packages\matplotlib\axes\_base.py", line 1453, in add_artist
    a.set_axes(self)
AttributeError: 'NoneType' object has no attribute 'set_axes'
06.15.2016 02:07:57 'NoneType' object has no attribute 'set_axes'
Traceback (most recent call last):
  File "Graph.py", line 805, in onNewLine
    self.corrLabel.writeCabLabel()
  File "Graph.py", line 1054, in writeCabLabel
    self.parent.host.add_artist(self.labelCable)
  File "C:\Python34\lib\site-packages\matplotlib\axes\_base.py", line 1453, in add_artist
    a.set_axes(self)
AttributeError: 'NoneType' object has no attribute 'set_axes'
06.15.2016 02:08:13 'NoneType' object has no attribute 'set_axes'
Traceback (most recent call last):
  File "Graph.py", line 805, in onNewLine
    self.corrLabel.writeCabLabel()
  File "Graph.py", line 1054, in writeCabLabel
    self.parent.host.add_artist(self.labelCable)
  File "C:\Python34\lib\site-packages\matplotlib\axes\_base.py", line 1453, in add_artist
    a.set_axes(self)
AttributeError: 'NoneType' object has no attribute 'set_axes'
06.15.2016 02:08:29 'NoneType' object has no attribute 'set_axes'
Traceback (most recent call last):
  File "Graph.py", line 805, in onNewLine
    self.corrLabel.writeCabLabel()
  File "Graph.py", line 1054, in writeCabLabel
    self.parent.host.add_artist(self.labelCable)
  File "C:\Python34\lib\site-packages\matplotlib\axes\_base.py", line 1453, in add_artist
    a.set_axes(self)
AttributeError: 'NoneType' object has no attribute 'set_axes'
06.15.2016 02:08:45 'NoneType' object has no attribute 'set_axes'
Traceback (most recent call last):
  File "Graph.py", line 805, in onNewLine
    self.corrLabel.writeCabLabel()
  File "Graph.py", line 1054, in writeCabLabel
    self.parent.host.add_artist(self.labelCable)
  File "C:\Python34\lib\site-packages\matplotlib\axes\_base.py", line 1453, in add_artist
    a.set_axes(self)
AttributeError: 'NoneType' object has no attribute 'set_axes'
06.15.2016 02:08:49 recv 1fd984 error WSAECONNRESET
06.15.2016 02:11:32 TMV3 Measurement started Meas
06.15.2016 02:11:49 'MainForm' object has no attribute 'draw'
Traceback (most recent call last):
  File "Graph.py", line 803, in onNewLine
    self.corrLabel.writeAntLabel()
  File "Graph.py", line 1047, in writeAntLabel
    self.parent.draw()
AttributeError: 'MainForm' object has no attribute 'draw'
06.15.2016 02:12:05 list.remove(x): x not in list
Traceback (most recent call last):
  File "Graph.py", line 803, in onNewLine
    self.corrLabel.writeAntLabel()
  File "Graph.py", line 1046, in writeAntLabel
    self.labelAntenna.remove()
  File "C:\Python34\lib\site-packages\matplotlib\artist.py", line 139, in remove
    self._remove_method(self)
  File "C:\Python34\lib\site-packages\matplotlib\axes\_axes.py", line 594, in <lambda>
    t._remove_method = lambda h: self.texts.remove(h)
ValueError: list.remove(x): x not in list
06.15.2016 02:32:25 TMV3 Measurement started Meas
06.15.2016 02:32:27 'MainForm' object has no attribute 'draw'
Traceback (most recent call last):
  File "Graph.py", line 803, in onNewLine
    self.corrLabel.writeAntLabel()
  File "Graph.py", line 1049, in writeAntLabel
    self.parent.draw()
AttributeError: 'MainForm' object has no attribute 'draw'
06.15.2016 02:32:27 'MainForm' object has no attribute 'draw'
Traceback (most recent call last):
  File "Graph.py", line 805, in onNewLine
    self.corrLabel.writeCabLabel()
  File "Graph.py", line 1057, in writeCabLabel
    self.parent.draw()
AttributeError: 'MainForm' object has no attribute 'draw'
06.15.2016 02:32:42 'MainForm' object has no attribute 'draw'
Traceback (most recent call last):
  File "Graph.py", line 803, in onNewLine
    self.corrLabel.writeAntLabel()
  File "Graph.py", line 1047, in writeAntLabel
    self.parent.draw()
AttributeError: 'MainForm' object has no attribute 'draw'
06.15.2016 02:32:42 'MainForm' object has no attribute 'draw'
Traceback (most recent call last):
  File "Graph.py", line 805, in onNewLine
    self.corrLabel.writeCabLabel()
  File "Graph.py", line 1055, in writeCabLabel
    self.parent.draw()
AttributeError: 'MainForm' object has no attribute 'draw'
06.15.2016 02:32:57 list.remove(x): x not in list
Traceback (most recent call last):
  File "Graph.py", line 803, in onNewLine
    self.corrLabel.writeAntLabel()
  File "Graph.py", line 1046, in writeAntLabel
    self.labelAntenna.remove()
  File "C:\Python34\lib\site-packages\matplotlib\artist.py", line 139, in remove
    self._remove_method(self)
  File "C:\Python34\lib\site-packages\matplotlib\axes\_axes.py", line 594, in <lambda>
    t._remove_method = lambda h: self.texts.remove(h)
ValueError: list.remove(x): x not in list
06.15.2016 02:32:57 list.remove(x): x not in list
Traceback (most recent call last):
  File "Graph.py", line 805, in onNewLine
    self.corrLabel.writeCabLabel()
  File "Graph.py", line 1054, in writeCabLabel
    self.labelCable.remove()
  File "C:\Python34\lib\site-packages\matplotlib\artist.py", line 139, in remove
    self._remove_method(self)
  File "C:\Python34\lib\site-packages\matplotlib\axes\_axes.py", line 594, in <lambda>
    t._remove_method = lambda h: self.texts.remove(h)
ValueError: list.remove(x): x not in list
06.15.2016 02:33:13 list.remove(x): x not in list
Traceback (most recent call last):
  File "Graph.py", line 803, in onNewLine
    self.corrLabel.writeAntLabel()
  File "Graph.py", line 1046, in writeAntLabel
    self.labelAntenna.remove()
  File "C:\Python34\lib\site-packages\matplotlib\artist.py", line 139, in remove
    self._remove_method(self)
  File "C:\Python34\lib\site-packages\matplotlib\axes\_axes.py", line 594, in <lambda>
    t._remove_method = lambda h: self.texts.remove(h)
ValueError: list.remove(x): x not in list
06.15.2016 02:33:13 list.remove(x): x not in list
Traceback (most recent call last):
  File "Graph.py", line 805, in onNewLine
    self.corrLabel.writeCabLabel()
  File "Graph.py", line 1054, in writeCabLabel
    self.labelCable.remove()
  File "C:\Python34\lib\site-packages\matplotlib\artist.py", line 139, in remove
    self._remove_method(self)
  File "C:\Python34\lib\site-packages\matplotlib\axes\_axes.py", line 594, in <lambda>
    t._remove_method = lambda h: self.texts.remove(h)
ValueError: list.remove(x): x not in list
06.15.2016 02:39:35 TMV3 Measurement started Meas
06.15.2016 02:39:36 'MainForm' object has no attribute 'draw'
Traceback (most recent call last):
  File "Graph.py", line 803, in onNewLine
    self.corrLabel.writeAntLabel()
  File "Graph.py", line 1049, in writeAntLabel
    self.parent.draw()
AttributeError: 'MainForm' object has no attribute 'draw'
06.15.2016 02:39:36 'MainForm' object has no attribute 'draw'
Traceback (most recent call last):
  File "Graph.py", line 805, in onNewLine
    self.corrLabel.writeCabLabel()
  File "Graph.py", line 1057, in writeCabLabel
    self.parent.draw()
AttributeError: 'MainForm' object has no attribute 'draw'
06.15.2016 02:39:52 set_position() takes 2 positional arguments but 3 were given
Traceback (most recent call last):
  File "Graph.py", line 803, in onNewLine
    self.corrLabel.writeAntLabel()
  File "Graph.py", line 1046, in writeAntLabel
    self.labelAntenna.set_position(x,self.parent.corrAntYEndPos)
TypeError: set_position() takes 2 positional arguments but 3 were given
06.15.2016 02:39:52 'MainForm' object has no attribute 'draw'
Traceback (most recent call last):
  File "Graph.py", line 805, in onNewLine
    self.corrLabel.writeCabLabel()
  File "Graph.py", line 1057, in writeCabLabel
    self.parent.draw()
AttributeError: 'MainForm' object has no attribute 'draw'
06.15.2016 02:40:08 set_position() takes 2 positional arguments but 3 were given
Traceback (most recent call last):
  File "Graph.py", line 803, in onNewLine
    self.corrLabel.writeAntLabel()
  File "Graph.py", line 1046, in writeAntLabel
    self.labelAntenna.set_position(x,self.parent.corrAntYEndPos)
TypeError: set_position() takes 2 positional arguments but 3 were given
06.15.2016 02:40:08 'MainForm' object has no attribute 'draw'
Traceback (most recent call last):
  File "Graph.py", line 805, in onNewLine
    self.corrLabel.writeCabLabel()
  File "Graph.py", line 1057, in writeCabLabel
    self.parent.draw()
AttributeError: 'MainForm' object has no attribute 'draw'
06.15.2016 02:40:23 set_position() takes 2 positional arguments but 3 were given
Traceback (most recent call last):
  File "Graph.py", line 803, in onNewLine
    self.corrLabel.writeAntLabel()
  File "Graph.py", line 1046, in writeAntLabel
    self.labelAntenna.set_position(x,self.parent.corrAntYEndPos)
TypeError: set_position() takes 2 positional arguments but 3 were given
06.15.2016 02:40:23 'MainForm' object has no attribute 'draw'
Traceback (most recent call last):
  File "Graph.py", line 805, in onNewLine
    self.corrLabel.writeCabLabel()
  File "Graph.py", line 1057, in writeCabLabel
    self.parent.draw()
AttributeError: 'MainForm' object has no attribute 'draw'
06.15.2016 02:41:04 recv 2fd1504 error WSAECONNRESET
06.15.2016 02:44:36 'MainForm' object has no attribute 'draw'
Traceback (most recent call last):
  File "Graph.py", line 809, in onNewLine
    self.corrLabel.writeAntLabel()
  File "Graph.py", line 1055, in writeAntLabel
    self.parent.draw()
AttributeError: 'MainForm' object has no attribute 'draw'
06.15.2016 02:44:36 'MainForm' object has no attribute 'draw'
Traceback (most recent call last):
  File "Graph.py", line 811, in onNewLine
    self.corrLabel.writeCabLabel()
  File "Graph.py", line 1063, in writeCabLabel
    self.parent.draw()
AttributeError: 'MainForm' object has no attribute 'draw'
06.15.2016 02:44:36 set_position() takes 2 positional arguments but 3 were given
Traceback (most recent call last):
  File "Graph.py", line 809, in onNewLine
    self.corrLabel.writeAntLabel()
  File "Graph.py", line 1052, in writeAntLabel
    self.labelAntenna.set_position(x,self.parent.corrAntYEndPos)
TypeError: set_position() takes 2 positional arguments but 3 were given
06.15.2016 02:44:36 'MainForm' object has no attribute 'draw'
Traceback (most recent call last):
  File "Graph.py", line 811, in onNewLine
    self.corrLabel.writeCabLabel()
  File "Graph.py", line 1063, in writeCabLabel
    self.parent.draw()
AttributeError: 'MainForm' object has no attribute 'draw'
06.15.2016 02:44:36 set_position() takes 2 positional arguments but 3 were given
Traceback (most recent call last):
  File "Graph.py", line 809, in onNewLine
    self.corrLabel.writeAntLabel()
  File "Graph.py", line 1052, in writeAntLabel
    self.labelAntenna.set_position(x,self.parent.corrAntYEndPos)
TypeError: set_position() takes 2 positional arguments but 3 were given
06.15.2016 02:44:36 'MainForm' object has no attribute 'draw'
Traceback (most recent call last):
  File "Graph.py", line 811, in onNewLine
    self.corrLabel.writeCabLabel()
  File "Graph.py", line 1063, in writeCabLabel
    self.parent.draw()
AttributeError: 'MainForm' object has no attribute 'draw'
06.15.2016 02:44:36 set_position() takes 2 positional arguments but 3 were given
Traceback (most recent call last):
  File "Graph.py", line 809, in onNewLine
    self.corrLabel.writeAntLabel()
  File "Graph.py", line 1052, in writeAntLabel
    self.labelAntenna.set_position(x,self.parent.corrAntYEndPos)
TypeError: set_position() takes 2 positional arguments but 3 were given
06.15.2016 02:44:36 'MainForm' object has no attribute 'draw'
Traceback (most recent call last):
  File "Graph.py", line 811, in onNewLine
    self.corrLabel.writeCabLabel()
  File "Graph.py", line 1063, in writeCabLabel
    self.parent.draw()
AttributeError: 'MainForm' object has no attribute 'draw'
06.15.2016 02:44:36 set_position() takes 2 positional arguments but 3 were given
Traceback (most recent call last):
  File "Graph.py", line 809, in onNewLine
    self.corrLabel.writeAntLabel()
  File "Graph.py", line 1052, in writeAntLabel
    self.labelAntenna.set_position(x,self.parent.corrAntYEndPos)
TypeError: set_position() takes 2 positional arguments but 3 were given
06.15.2016 02:44:36 'MainForm' object has no attribute 'draw'
Traceback (most recent call last):
  File "Graph.py", line 811, in onNewLine
    self.corrLabel.writeCabLabel()
  File "Graph.py", line 1063, in writeCabLabel
    self.parent.draw()
AttributeError: 'MainForm' object has no attribute 'draw'
06.15.2016 02:44:36 set_position() takes 2 positional arguments but 3 were given
Traceback (most recent call last):
  File "Graph.py", line 809, in onNewLine
    self.corrLabel.writeAntLabel()
  File "Graph.py", line 1052, in writeAntLabel
    self.labelAntenna.set_position(x,self.parent.corrAntYEndPos)
TypeError: set_position() takes 2 positional arguments but 3 were given
06.15.2016 02:44:36 'MainForm' object has no attribute 'draw'
Traceback (most recent call last):
  File "Graph.py", line 811, in onNewLine
    self.corrLabel.writeCabLabel()
  File "Graph.py", line 1063, in writeCabLabel
    self.parent.draw()
AttributeError: 'MainForm' object has no attribute 'draw'
06.15.2016 02:46:00 'MainForm' object has no attribute 'draw'
Traceback (most recent call last):
  File "Graph.py", line 809, in onNewLine
    self.corrLabel.writeAntLabel()
  File "Graph.py", line 1055, in writeAntLabel
    self.parent.draw()
AttributeError: 'MainForm' object has no attribute 'draw'
06.15.2016 02:46:00 'MainForm' object has no attribute 'draw'
Traceback (most recent call last):
  File "Graph.py", line 811, in onNewLine
    self.corrLabel.writeCabLabel()
  File "Graph.py", line 1063, in writeCabLabel
    self.parent.draw()
AttributeError: 'MainForm' object has no attribute 'draw'
06.15.2016 02:46:00 set_position() takes 2 positional arguments but 3 were given
Traceback (most recent call last):
  File "Graph.py", line 809, in onNewLine
    self.corrLabel.writeAntLabel()
  File "Graph.py", line 1052, in writeAntLabel
    self.labelAntenna.set_position(x,self.parent.corrAntYEndPos)
TypeError: set_position() takes 2 positional arguments but 3 were given
06.15.2016 02:46:00 'MainForm' object has no attribute 'draw'
Traceback (most recent call last):
  File "Graph.py", line 811, in onNewLine
    self.corrLabel.writeCabLabel()
  File "Graph.py", line 1063, in writeCabLabel
    self.parent.draw()
AttributeError: 'MainForm' object has no attribute 'draw'
06.15.2016 02:46:00 set_position() takes 2 positional arguments but 3 were given
Traceback (most recent call last):
  File "Graph.py", line 809, in onNewLine
    self.corrLabel.writeAntLabel()
  File "Graph.py", line 1052, in writeAntLabel
    self.labelAntenna.set_position(x,self.parent.corrAntYEndPos)
TypeError: set_position() takes 2 positional arguments but 3 were given
06.15.2016 02:46:00 'MainForm' object has no attribute 'draw'
Traceback (most recent call last):
  File "Graph.py", line 811, in onNewLine
    self.corrLabel.writeCabLabel()
  File "Graph.py", line 1063, in writeCabLabel
    self.parent.draw()
AttributeError: 'MainForm' object has no attribute 'draw'
06.15.2016 02:46:00 set_position() takes 2 positional arguments but 3 were given
Traceback (most recent call last):
  File "Graph.py", line 809, in onNewLine
    self.corrLabel.writeAntLabel()
  File "Graph.py", line 1052, in writeAntLabel
    self.labelAntenna.set_position(x,self.parent.corrAntYEndPos)
TypeError: set_position() takes 2 positional arguments but 3 were given
06.15.2016 02:46:00 'MainForm' object has no attribute 'draw'
Traceback (most recent call last):
  File "Graph.py", line 811, in onNewLine
    self.corrLabel.writeCabLabel()
  File "Graph.py", line 1063, in writeCabLabel
    self.parent.draw()
AttributeError: 'MainForm' object has no attribute 'draw'
06.15.2016 02:46:00 set_position() takes 2 positional arguments but 3 were given
Traceback (most recent call last):
  File "Graph.py", line 809, in onNewLine
    self.corrLabel.writeAntLabel()
  File "Graph.py", line 1052, in writeAntLabel
    self.labelAntenna.set_position(x,self.parent.corrAntYEndPos)
TypeError: set_position() takes 2 positional arguments but 3 were given
06.15.2016 02:46:00 'MainForm' object has no attribute 'draw'
Traceback (most recent call last):
  File "Graph.py", line 811, in onNewLine
    self.corrLabel.writeCabLabel()
  File "Graph.py", line 1063, in writeCabLabel
    self.parent.draw()
AttributeError: 'MainForm' object has no attribute 'draw'
06.15.2016 02:46:00 set_position() takes 2 positional arguments but 3 were given
Traceback (most recent call last):
  File "Graph.py", line 809, in onNewLine
    self.corrLabel.writeAntLabel()
  File "Graph.py", line 1052, in writeAntLabel
    self.labelAntenna.set_position(x,self.parent.corrAntYEndPos)
TypeError: set_position() takes 2 positional arguments but 3 were given
06.15.2016 02:46:00 'MainForm' object has no attribute 'draw'
Traceback (most recent call last):
  File "Graph.py", line 811, in onNewLine
    self.corrLabel.writeCabLabel()
  File "Graph.py", line 1063, in writeCabLabel
    self.parent.draw()
AttributeError: 'MainForm' object has no attribute 'draw'
06.15.2016 02:47:48 'MainForm' object has no attribute 'draw'
Traceback (most recent call last):
  File "Graph.py", line 809, in onNewLine
    self.corrLabel.writeAntLabel()
  File "Graph.py", line 1055, in writeAntLabel
    self.parent.draw()
AttributeError: 'MainForm' object has no attribute 'draw'
06.15.2016 02:47:48 'MainForm' object has no attribute 'draw'
Traceback (most recent call last):
  File "Graph.py", line 811, in onNewLine
    self.corrLabel.writeCabLabel()
  File "Graph.py", line 1063, in writeCabLabel
    self.parent.draw()
AttributeError: 'MainForm' object has no attribute 'draw'
06.15.2016 02:47:48 set_position() takes 2 positional arguments but 3 were given
Traceback (most recent call last):
  File "Graph.py", line 809, in onNewLine
    self.corrLabel.writeAntLabel()
  File "Graph.py", line 1052, in writeAntLabel
    self.labelAntenna.set_position(x,self.parent.corrAntYEndPos)
TypeError: set_position() takes 2 positional arguments but 3 were given
06.15.2016 02:47:48 'MainForm' object has no attribute 'draw'
Traceback (most recent call last):
  File "Graph.py", line 811, in onNewLine
    self.corrLabel.writeCabLabel()
  File "Graph.py", line 1063, in writeCabLabel
    self.parent.draw()
AttributeError: 'MainForm' object has no attribute 'draw'
06.15.2016 02:47:48 set_position() takes 2 positional arguments but 3 were given
Traceback (most recent call last):
  File "Graph.py", line 809, in onNewLine
    self.corrLabel.writeAntLabel()
  File "Graph.py", line 1052, in writeAntLabel
    self.labelAntenna.set_position(x,self.parent.corrAntYEndPos)
TypeError: set_position() takes 2 positional arguments but 3 were given
06.15.2016 02:47:48 'MainForm' object has no attribute 'draw'
Traceback (most recent call last):
  File "Graph.py", line 811, in onNewLine
    self.corrLabel.writeCabLabel()
  File "Graph.py", line 1063, in writeCabLabel
    self.parent.draw()
AttributeError: 'MainForm' object has no attribute 'draw'
06.15.2016 02:47:48 set_position() takes 2 positional arguments but 3 were given
Traceback (most recent call last):
  File "Graph.py", line 809, in onNewLine
    self.corrLabel.writeAntLabel()
  File "Graph.py", line 1052, in writeAntLabel
    self.labelAntenna.set_position(x,self.parent.corrAntYEndPos)
TypeError: set_position() takes 2 positional arguments but 3 were given
06.15.2016 02:47:48 'MainForm' object has no attribute 'draw'
Traceback (most recent call last):
  File "Graph.py", line 811, in onNewLine
    self.corrLabel.writeCabLabel()
  File "Graph.py", line 1063, in writeCabLabel
    self.parent.draw()
AttributeError: 'MainForm' object has no attribute 'draw'
06.15.2016 02:47:48 set_position() takes 2 positional arguments but 3 were given
Traceback (most recent call last):
  File "Graph.py", line 809, in onNewLine
    self.corrLabel.writeAntLabel()
  File "Graph.py", line 1052, in writeAntLabel
    self.labelAntenna.set_position(x,self.parent.corrAntYEndPos)
TypeError: set_position() takes 2 positional arguments but 3 were given
06.15.2016 02:47:48 'MainForm' object has no attribute 'draw'
Traceback (most recent call last):
  File "Graph.py", line 811, in onNewLine
    self.corrLabel.writeCabLabel()
  File "Graph.py", line 1063, in writeCabLabel
    self.parent.draw()
AttributeError: 'MainForm' object has no attribute 'draw'
06.15.2016 02:47:48 set_position() takes 2 positional arguments but 3 were given
Traceback (most recent call last):
  File "Graph.py", line 809, in onNewLine
    self.corrLabel.writeAntLabel()
  File "Graph.py", line 1052, in writeAntLabel
    self.labelAntenna.set_position(x,self.parent.corrAntYEndPos)
TypeError: set_position() takes 2 positional arguments but 3 were given
06.15.2016 02:47:48 'MainForm' object has no attribute 'draw'
Traceback (most recent call last):
  File "Graph.py", line 811, in onNewLine
    self.corrLabel.writeCabLabel()
  File "Graph.py", line 1063, in writeCabLabel
    self.parent.draw()
AttributeError: 'MainForm' object has no attribute 'draw'
06.15.2016 02:52:01 'MainForm' object has no attribute 'draw'
Traceback (most recent call last):
  File "Graph.py", line 809, in onNewLine
    self.corrLabel.writeAntLabel()
  File "Graph.py", line 1055, in writeAntLabel
    self.parent.draw()
AttributeError: 'MainForm' object has no attribute 'draw'
06.15.2016 02:52:01 'MainForm' object has no attribute 'draw'
Traceback (most recent call last):
  File "Graph.py", line 811, in onNewLine
    self.corrLabel.writeCabLabel()
  File "Graph.py", line 1063, in writeCabLabel
    self.parent.draw()
AttributeError: 'MainForm' object has no attribute 'draw'
06.15.2016 02:52:01 set_position() takes 2 positional arguments but 3 were given
Traceback (most recent call last):
  File "Graph.py", line 809, in onNewLine
    self.corrLabel.writeAntLabel()
  File "Graph.py", line 1052, in writeAntLabel
    self.labelAntenna.set_position(x,self.parent.corrAntYEndPos)
TypeError: set_position() takes 2 positional arguments but 3 were given
06.15.2016 02:52:01 'MainForm' object has no attribute 'draw'
Traceback (most recent call last):
  File "Graph.py", line 811, in onNewLine
    self.corrLabel.writeCabLabel()
  File "Graph.py", line 1063, in writeCabLabel
    self.parent.draw()
AttributeError: 'MainForm' object has no attribute 'draw'
06.15.2016 02:52:01 set_position() takes 2 positional arguments but 3 were given
Traceback (most recent call last):
  File "Graph.py", line 809, in onNewLine
    self.corrLabel.writeAntLabel()
  File "Graph.py", line 1052, in writeAntLabel
    self.labelAntenna.set_position(x,self.parent.corrAntYEndPos)
TypeError: set_position() takes 2 positional arguments but 3 were given
06.15.2016 02:52:01 'MainForm' object has no attribute 'draw'
Traceback (most recent call last):
  File "Graph.py", line 811, in onNewLine
    self.corrLabel.writeCabLabel()
  File "Graph.py", line 1063, in writeCabLabel
    self.parent.draw()
AttributeError: 'MainForm' object has no attribute 'draw'
06.15.2016 02:52:01 set_position() takes 2 positional arguments but 3 were given
Traceback (most recent call last):
  File "Graph.py", line 809, in onNewLine
    self.corrLabel.writeAntLabel()
  File "Graph.py", line 1052, in writeAntLabel
    self.labelAntenna.set_position(x,self.parent.corrAntYEndPos)
TypeError: set_position() takes 2 positional arguments but 3 were given
06.15.2016 02:52:01 'MainForm' object has no attribute 'draw'
Traceback (most recent call last):
  File "Graph.py", line 811, in onNewLine
    self.corrLabel.writeCabLabel()
  File "Graph.py", line 1063, in writeCabLabel
    self.parent.draw()
AttributeError: 'MainForm' object has no attribute 'draw'
06.15.2016 02:52:01 set_position() takes 2 positional arguments but 3 were given
Traceback (most recent call last):
  File "Graph.py", line 809, in onNewLine
    self.corrLabel.writeAntLabel()
  File "Graph.py", line 1052, in writeAntLabel
    self.labelAntenna.set_position(x,self.parent.corrAntYEndPos)
TypeError: set_position() takes 2 positional arguments but 3 were given
06.15.2016 02:52:01 'MainForm' object has no attribute 'draw'
Traceback (most recent call last):
  File "Graph.py", line 811, in onNewLine
    self.corrLabel.writeCabLabel()
  File "Graph.py", line 1063, in writeCabLabel
    self.parent.draw()
AttributeError: 'MainForm' object has no attribute 'draw'
06.15.2016 02:52:01 set_position() takes 2 positional arguments but 3 were given
Traceback (most recent call last):
  File "Graph.py", line 809, in onNewLine
    self.corrLabel.writeAntLabel()
  File "Graph.py", line 1052, in writeAntLabel
    self.labelAntenna.set_position(x,self.parent.corrAntYEndPos)
TypeError: set_position() takes 2 positional arguments but 3 were given
06.15.2016 02:52:01 'MainForm' object has no attribute 'draw'
Traceback (most recent call last):
  File "Graph.py", line 811, in onNewLine
    self.corrLabel.writeCabLabel()
  File "Graph.py", line 1063, in writeCabLabel
    self.parent.draw()
AttributeError: 'MainForm' object has no attribute 'draw'
06.15.2016 02:54:28 'MainForm' object has no attribute 'draw'
Traceback (most recent call last):
  File "Graph.py", line 811, in onNewLine
    self.corrLabel.writeAntLabel()
  File "Graph.py", line 1057, in writeAntLabel
    self.parent.draw()
AttributeError: 'MainForm' object has no attribute 'draw'
06.15.2016 02:54:28 'MainForm' object has no attribute 'draw'
Traceback (most recent call last):
  File "Graph.py", line 813, in onNewLine
    self.corrLabel.writeCabLabel()
  File "Graph.py", line 1065, in writeCabLabel
    self.parent.draw()
AttributeError: 'MainForm' object has no attribute 'draw'
06.15.2016 02:54:28 set_position() takes 2 positional arguments but 3 were given
Traceback (most recent call last):
  File "Graph.py", line 811, in onNewLine
    self.corrLabel.writeAntLabel()
  File "Graph.py", line 1054, in writeAntLabel
    self.labelAntenna.set_position(x,self.parent.corrAntYEndPos)
TypeError: set_position() takes 2 positional arguments but 3 were given
06.15.2016 02:54:28 'MainForm' object has no attribute 'draw'
Traceback (most recent call last):
  File "Graph.py", line 813, in onNewLine
    self.corrLabel.writeCabLabel()
  File "Graph.py", line 1065, in writeCabLabel
    self.parent.draw()
AttributeError: 'MainForm' object has no attribute 'draw'
06.15.2016 02:54:28 set_position() takes 2 positional arguments but 3 were given
Traceback (most recent call last):
  File "Graph.py", line 811, in onNewLine
    self.corrLabel.writeAntLabel()
  File "Graph.py", line 1054, in writeAntLabel
    self.labelAntenna.set_position(x,self.parent.corrAntYEndPos)
TypeError: set_position() takes 2 positional arguments but 3 were given
06.15.2016 02:54:28 'MainForm' object has no attribute 'draw'
Traceback (most recent call last):
  File "Graph.py", line 813, in onNewLine
    self.corrLabel.writeCabLabel()
  File "Graph.py", line 1065, in writeCabLabel
    self.parent.draw()
AttributeError: 'MainForm' object has no attribute 'draw'
06.15.2016 02:54:28 set_position() takes 2 positional arguments but 3 were given
Traceback (most recent call last):
  File "Graph.py", line 811, in onNewLine
    self.corrLabel.writeAntLabel()
  File "Graph.py", line 1054, in writeAntLabel
    self.labelAntenna.set_position(x,self.parent.corrAntYEndPos)
TypeError: set_position() takes 2 positional arguments but 3 were given
06.15.2016 02:54:28 'MainForm' object has no attribute 'draw'
Traceback (most recent call last):
  File "Graph.py", line 813, in onNewLine
    self.corrLabel.writeCabLabel()
  File "Graph.py", line 1065, in writeCabLabel
    self.parent.draw()
AttributeError: 'MainForm' object has no attribute 'draw'
06.15.2016 02:54:28 set_position() takes 2 positional arguments but 3 were given
Traceback (most recent call last):
  File "Graph.py", line 811, in onNewLine
    self.corrLabel.writeAntLabel()
  File "Graph.py", line 1054, in writeAntLabel
    self.labelAntenna.set_position(x,self.parent.corrAntYEndPos)
TypeError: set_position() takes 2 positional arguments but 3 were given
06.15.2016 02:54:28 'MainForm' object has no attribute 'draw'
Traceback (most recent call last):
  File "Graph.py", line 813, in onNewLine
    self.corrLabel.writeCabLabel()
  File "Graph.py", line 1065, in writeCabLabel
    self.parent.draw()
AttributeError: 'MainForm' object has no attribute 'draw'
06.15.2016 02:54:28 set_position() takes 2 positional arguments but 3 were given
Traceback (most recent call last):
  File "Graph.py", line 811, in onNewLine
    self.corrLabel.writeAntLabel()
  File "Graph.py", line 1054, in writeAntLabel
    self.labelAntenna.set_position(x,self.parent.corrAntYEndPos)
TypeError: set_position() takes 2 positional arguments but 3 were given
06.15.2016 02:54:28 'MainForm' object has no attribute 'draw'
Traceback (most recent call last):
  File "Graph.py", line 813, in onNewLine
    self.corrLabel.writeCabLabel()
  File "Graph.py", line 1065, in writeCabLabel
    self.parent.draw()
AttributeError: 'MainForm' object has no attribute 'draw'
06.15.2016 02:54:58 recv 1fd1404 error WSAECONNRESET
06.15.2016 03:08:44 recv 1fd1428 error WSAECONNRESET
06.15.2016 03:08:44 TMV3 Measurement started Meas
06.15.2016 05:12:05 recv 3fd1508 error WSAECONNRESET
06.16.2016 09:41:43 TMV3 Measurement started Meas
06.16.2016 10:04:58 recv 3fd1564 error WSAECONNRESET
06.16.2016 10:16:50 TMV3 Measurement started Meas
06.16.2016 11:00:21 TMV3 Measurement started Meas
06.16.2016 11:00:30 recv 2fd1488 error WSAECONNRESET
06.16.2016 11:08:35 TMV3 Measurement started Meas
06.16.2016 11:08:59 recv 1fd968 error WSAECONNRESET
06.16.2016 11:12:30 TMV3 Measurement started Meas
06.16.2016 11:12:48 recv 2fd1476 error WSAECONNRESET
06.16.2016 11:12:49 recv 1fd996 error WSAECONNRESET
06.16.2016 11:12:50 TMV3 Measurement started Meas
06.16.2016 11:12:51 recv 4fd1524 error WSAECONNRESET
06.16.2016 11:13:56 TMV3 Measurement started Meas
06.16.2016 11:19:47 TMV3 Measurement started Meas
06.16.2016 11:20:18 recv 2fd1496 error WSAECONNRESET
06.21.2016 10:23:12 TMV3 Measurement started Meas
06.21.2016 10:23:23 recv 1fd944 error WSAECONNRESET
06.21.2016 11:23:50 recv 1fd1408 error WSAECONNRESET
