06.30.2016 10:58:13 TMV3 Measurement started Meas
06.30.2016 10:58:14 __init__() takes 1 positional argument but 2 were given Meas
Traceback (most recent call last):
  File "Measurement.py", line 236, in parser
    _rt = _py_mod_class(self)
TypeError: __init__() takes 1 positional argument but 2 were given
06.30.2016 10:58:14 __init__() takes 1 positional argument but 2 were given Meas
Traceback (most recent call last):
  File "Measurement.py", line 236, in parser
    _rt = _py_mod_class(self)
TypeError: __init__() takes 1 positional argument but 2 were given
06.30.2016 10:58:14 __init__() takes 1 positional argument but 2 were given Meas
Traceback (most recent call last):
  File "Measurement.py", line 236, in parser
    _rt = _py_mod_class(self)
TypeError: __init__() takes 1 positional argument but 2 were given
06.30.2016 10:58:14 __init__() takes 1 positional argument but 2 were given Meas
Traceback (most recent call last):
  File "Measurement.py", line 236, in parser
    _rt = _py_mod_class(self)
TypeError: __init__() takes 1 positional argument but 2 were given
06.30.2016 10:58:14 __init__() takes 1 positional argument but 2 were given Meas
Traceback (most recent call last):
  File "Measurement.py", line 236, in parser
    _rt = _py_mod_class(self)
TypeError: __init__() takes 1 positional argument but 2 were given
06.30.2016 10:58:15 __init__() takes 1 positional argument but 2 were given Meas
Traceback (most recent call last):
  File "Measurement.py", line 236, in parser
    _rt = _py_mod_class(self)
TypeError: __init__() takes 1 positional argument but 2 were given
06.30.2016 10:58:15 __init__() takes 1 positional argument but 2 were given Meas
Traceback (most recent call last):
  File "Measurement.py", line 236, in parser
    _rt = _py_mod_class(self)
TypeError: __init__() takes 1 positional argument but 2 were given
06.30.2016 10:58:15 __init__() takes 1 positional argument but 2 were given Meas
Traceback (most recent call last):
  File "Measurement.py", line 236, in parser
    _rt = _py_mod_class(self)
TypeError: __init__() takes 1 positional argument but 2 were given
06.30.2016 10:58:15 __init__() takes 1 positional argument but 2 were given Meas
Traceback (most recent call last):
  File "Measurement.py", line 236, in parser
    _rt = _py_mod_class(self)
TypeError: __init__() takes 1 positional argument but 2 were given
06.30.2016 10:58:15 __init__() takes 1 positional argument but 2 were given Meas
Traceback (most recent call last):
  File "Measurement.py", line 236, in parser
    _rt = _py_mod_class(self)
TypeError: __init__() takes 1 positional argument but 2 were given
06.30.2016 10:58:15 __init__() takes 1 positional argument but 2 were given Meas
Traceback (most recent call last):
  File "Measurement.py", line 236, in parser
    _rt = _py_mod_class(self)
TypeError: __init__() takes 1 positional argument but 2 were given
06.30.2016 10:58:19 recv 2fd1496 error WSAECONNRESET
06.30.2016 11:00:07 TMV3 Measurement started Meas
06.30.2016 11:01:55 recv 2fd1496 error WSAECONNRESET
06.30.2016 11:14:12 TMV3 Measurement started Meas
